# Generated by Django 3.1.7 on 2021-03-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='similarity',
            field=models.FloatField(default=0),
        ),
    ]
