# Generated by Django 3.1.7 on 2021-03-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210327_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='song1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='music.song'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='song2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
