# Generated by Django 3.1.7 on 2021-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210328_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genera',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='style',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.TextField(),
        ),
    ]
